version: 1.0.{build}
branches:
  only:
  - m/appveyor-min-master-nodes 
install:
- cmd: git submodule update --init -- es/upstream
build_script:
- cmd: gradlew.bat compileJava
test_script:
- ps: for($i=1; $i -le 20; $i++){gradlew.bat "-Dtest.single=SysCheckerIntegrationTest" :sql:test}
